/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'djtazzmtl' at '9/29/16 8:40 PM' with Gradle 2.14
 *
 * @author djtazzmtl, @date 9/29/16 8:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
